In [ ]:
# Import Numpy
# numpy.array   One Diamentional
# Two diamentional
# A + B
# A - B
# A*B


# numpy as np
# np.array  
# A+B  
# A-B
# A*B
# m*A   Scalar multiplication

# m by n matrix
# A +B,....


# Matrix multiplication  np.dot(A,B)



# linear algebra inverse
# np.linalg.inv(A)
# np.linalg.det(A)
# np.linalg.Matrix_rank(A)
# np.transpose(A)

In [1]:
import numpy as np

In [47]:
M = np.array([1])
M.shape

(1,)

In [48]:
A = np.array([[1,2,3]])
B = np.array([3,4,5])

In [43]:
A.shape

(1, 3)

In [5]:
A+B

array([4, 6, 8])

In [6]:
A-B

array([-2, -2, -2])

In [7]:
A*B

array([ 3,  8, 15])

In [8]:
np.dot(A,B)

26

In [37]:
A = np.array([[1,2,4,66,178,890,67],
             [3,55,77,990,123,578,389],
             [123,456,789,9876,45,64,333],
            [123,654,789,40,12,67,8],
            [123,654,76,7890,9000,456,789],
            [123,4956,789,9876,45,64,333],
            [123,654,789,40,12,67,348]])

In [38]:
A.shape

(7, 7)

In [39]:
m,n = A.shape

In [40]:
m

7

In [41]:
n

7

In [33]:
np.linalg.inv(A)

array([[ 6.90802043e-02, -1.07532267e-01,  1.00219634e-02,
        -9.93714467e-02,  5.21551551e-05,  2.54631234e-04,
         9.92338887e-02],
       [ 0.00000000e+00,  0.00000000e+00, -2.22222222e-04,
         0.00000000e+00,  0.00000000e+00,  2.22222222e-04,
         0.00000000e+00],
       [-1.08639126e-02,  1.67623095e-02, -1.38246709e-03,
         1.67697871e-02, -7.91310214e-06, -2.24154491e-04,
        -1.54757647e-02],
       [ 3.47721622e-06, -4.57497434e-06,  9.78610395e-05,
        -9.47783025e-06, -3.82368681e-07,  4.54827224e-06,
        -9.24657981e-05],
       [-9.20186332e-04,  1.34336087e-03, -1.96327359e-04,
         1.48456826e-03,  1.11934354e-04, -2.19390391e-05,
        -1.40351992e-03],
       [ 1.27858328e-03, -2.22846356e-04,  2.74604390e-05,
        -3.85129117e-05, -2.23815522e-05,  4.27247783e-06,
         2.42018381e-05],
       [-0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        -2.94117647e-03, -0.00000000e+00, -0.00000000e+00,
         2.9411764

In [34]:
np.linalg.det(A)

8.725656949489558e+20

In [18]:
A = np.array([[1,2,3],[0,2,4]])
B = np.array([[2,3,4],[1,2,5],[3,6,5]])
np.dot(A,B)

array([[13, 25, 29],
       [14, 28, 30]])

In [21]:
import numpy.linalg as lng

In [22]:
lng.inv(B)

array([[ 2.00000000e+00, -9.00000000e-01, -7.00000000e-01],
       [-1.00000000e+00,  2.00000000e-01,  6.00000000e-01],
       [ 3.33066907e-17,  3.00000000e-01, -1.00000000e-01]])

In [23]:
np.linalg.inv([[1,1,1],[1,0,1],[1,1,0]])

array([[-1.,  1.,  1.],
       [ 1., -1., -0.],
       [ 1., -0., -1.]])

In [24]:
np.linalg.det([[1,1,1],[1,0,1],[1,1,0]])

1.0

In [25]:
np.linalg.det([[1,1,1],[1,1,1],[1,1,1]])

0.0

In [27]:
np.linalg.matrix_rank([[1,1,1],[1,1,1],[1,1,1]])

1

In [28]:
np.linalg.matrix_rank([[1,1,1],[1,0,1],[1,1,0]])

3

In [30]:
np.transpose([[1,2,5],[1,0,1],[1,1,0]])

array([[1, 1, 1],
       [2, 0, 1],
       [5, 1, 0]])

In [16]:
import numpy

In [17]:
numpy.linalg.inv(np.array([[2,3,4],[1,2,5],[3,6,5]]))

array([[ 2.00000000e+00, -9.00000000e-01, -7.00000000e-01],
       [-1.00000000e+00,  2.00000000e-01,  6.00000000e-01],
       [ 3.33066907e-17,  3.00000000e-01, -1.00000000e-01]])