In [2]:
# M1 C

## ADDITION

In [1]:
3+5

8

## SUBTRACTION

In [2]:
3-6

-3

MULTIPLICATION

In [3]:
5*7

35

DIVISION

In [8]:
8/2

4.0

REMINDER

In [7]:
8%2

0

# 1) Using if, print Yes, if given number is even, otherwise print No

In [9]:
x=6
if x %2 ==0: 
    print("Yes")
else:
    print("No")

Yes


# USER DEFINED FUNCTION

In [12]:
def addition(u,v):
    z = u + v
    print(f"Sum is {z}")

In [13]:
addition(5,7)

Sum is 12


In [14]:
addition(4250,5698214487885232)

Sum is 5698214487889482


# Define a function that print square of a number if the number is even, or print half if the number os odd

In [18]:
def oddeven(u):
    if u%2==0:
        print(f'{u**2}')
    else:
        print(f'{u/2}')

In [17]:
oddeven(2)

4


## NUMPY

In [25]:
#Numpy
import numpy as np
A=np.array([[1,3,6]])
B=np.array([[2,8,9]])
print("Matrix A= ",A)
print("Matrix B= ",B)
A.shape


Matrix A=  [[1 3 6]]
Matrix B=  [[2 8 9]]


(1, 3)

In [29]:
#Matrix Addition, Multiplication 

sum_AB= np.add(A,B)
Diff_AB=np.subtract(A,B)
print("Sum of A and B = ", sum_AB)
print("Difference of A and B = ", Diff_AB)

Sum of A and B =  [[ 3 11 15]]
Difference of A and B =  [[-1 -5 -3]]


In [30]:
# write two 2x2 matrix and find sum and product of matrices

In [39]:
A=np.array([[1,2],[4,8]])
print("A = \n",A)
B=np.array([[3,2],[4,1]])
print("B = \n",B)
product_AB=np.dot(A,B)
print("A*B=",product_AB)

A = 
 [[1 2]
 [4 8]]
B = 
 [[3 2]
 [4 1]]
A*B= [[11  4]
 [44 16]]


In [45]:
#Determinant 
A=np.array([[2,1,3,4],[0,-1,2,1],[3,2,0,5],[-1,3,2,1]])
print("A=\n",A)
det=np.linalg.det(A)
print("determinant =",round(det))

A=
 [[ 2  1  3  4]
 [ 0 -1  2  1]
 [ 3  2  0  5]
 [-1  3  2  1]]
determinant = 35


In [48]:
B=np.array([[1,3],[2,8]])
inverse=np.linalg.inv(B)
print("inverse of A\n =",inverse)

inverse of A
 = [[ 4.  -1.5]
 [-1.   0.5]]
